#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Error: Missing IP address argument"
  echo "Usage: ./fastscan <IP>"
  exit 1
fi

IP=$1

sudo masscan -p1-65535 $IP --rate=1000 --wait=0 -e tun0 -oG masscan_oG_$IP.txt

tcp_ports=$(cat masscan_oG_$IP.txt | grep "open/tcp" | awk '{print $7}' | cut -d'/' -f1 | tr '\n' ',' | sed 's/,$//')

sudo nmap -e tun0 -A -v -p $tcp_ports -Pn -oN nmap_A_ports_$IP.txt $IP